#!/dmp/resources/prod/tools/system/python/Python-2.7.3/bin/python
# -*- coding: utf-8 -*-
import os
import sys
import csv
import argparse
import re
import inspect
import subprocess
import json,requests,ast
from os.path import basename
from mskcc.dmp.cvr.utils.dmp_logger import DMPLogger
from mskcc.dmp.cvr.utils.dmp_properties import Properties
#from app.lib.cvr.ui.utils.ui_properties import Properties
from org.mskcc.dmp.dmutils.dmp_db import DMPdb
import urllib2,requests,json
from requests.auth import HTTPDigestAuth
import urllib2, base64
from base64 import b64encode
import httplib

class AddSnp2Sample(object):
	dbObj = None
	sample_id = None

	def __init__(self,sample_id ):
		self.sample_id  = sample_id
		self.dbObj = self.getCVRDBHandle()

	def getCVRDBHandle(self):
		propObj = Properties()
		logger = DMPLogger()
		dbObj = None
		logger = logger.getCVRLogger("getCVRDBHandle")
 		logger.debug("Creating database connection for Adding snp_indel for a sample ")
 		logger.debug(propObj.config_file)
 		logger.debug(inspect.getfile(Properties) )
 		logger.debug( "%s - %s - %s-%s"%(propObj.getCVRDBUser(),propObj.getCVRDBServer(),propObj.getCVRDBName(),propObj.getCVRDBPass()))
   		try:
        			dbObj = DMPdb(
                       	propObj.getCVRDBUser(),
                       	propObj.getCVRDBPass(),
                       	propObj.getCVRDBServer(),
                       	propObj.getCVRDBName()
			)
		except Exception as e:
        			logger.error(e)
        			dbObj = None
        			raise("Database handle not created!")
    		return dbObj

    	def getDBObject(self):
    		return self.dbObj

    	def addSNP2Sample(self):
    		logger = DMPLogger()
		logger = logger.getCVRLogger("add Snp Indel to Sample ")
		logger.debug("Check if dmp_sample_id is in dmp_sample  table")
		dbObj = self.getCVRDBHandle()
 		dbObj.connect() #need to connect to the cvr db
 		retVal = True



def main():
	# Setting up argparse,accepting user input arguments to generate command line
	parser = argparse.ArgumentParser(description=__doc__,
                                 epilog="""If you have any questions,please
                                 contact wangy6@mskcc.org""")

	parser.add_argument('-s','--sample_id',action='store', dest='dmp_sample_id',
                    required=False, help='***Checking dmp_sample object*** \n'+
                                'Please give the sid that needs to be loaded\n')
	user_args = parser.parse_args()
	try :
		sid = user_args.dmp_sample_id
	except:
		sid = ''

	addobj = AddSnp2Sample(sid)

